version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - db
    networks:
      - python-grpc-network
  client:
    build: ./client
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - server
      - db
  db:
    image: mysql:latest
    container_name: grpc_db
    networks:
      - python-grpc-network
    environment:
      MYSQL_DATABASE: grpc_db
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "grpc_user"
      MYSQL_PASSWORD: "grpc_user"
    ports:
      - "3306:3306"

networks:
  python-grpc-network:
    driver: bridge
    name: python-grpc-network